[workspace]
members = ["crates/atif-arrow", "crates/atif-arrow-cli"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/dentiny/atif-arrow"

[workspace.dependencies]
arrow-array = "58"
arrow-json = "58"
arrow-schema = "58"
atif-arrow = { path = "crates/atif-arrow", version = "0.1.0" }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["arbitrary_precision"] }
serde_path_to_error = "0.1"
