[package]
name = "atif-arrow"
description = "An Arrow schema and conversion library for ATIF agent trajectories"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
arrow-array.workspace = true
arrow-json.workspace = true
arrow-schema.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_path_to_error.workspace = true
